### ISSUE TITLE
bochs displays transparent window however qemu runs fine

### ISSUE THREAD

**Issue by Shadowblitz16** [OrdoFlammae/littleosbook-src#11]
Boch displays a transparent window when the display library is set to sdl2 
I can't run it at all with sdl due to lack of information how to get the libraries.

Qemu runs the os fine but this tutorial doesn't use it which makes following the tutorial even harder

**Comment by FitDavid** [comment]
For me it only worked with _display_library: x_ in bochsrc.txt. For this too work you'll also need the bochs-x package. I tried sdl and sdl2 as well, but they didn't work for me either. I am on Debian 10. Also you're gonna need to type _continue_ in terminal window after bochs starts.

**Comment by Shadowblitz16** [comment]
I am no longer using bochs or have it installed on my system.
I don't think the issue was resolved but you can close this.
I am no longer able to test it and I don't remember what the issue is.
I don't know when I will install it again as I was just using qemu.

**Comment by OrdoFlammae** [comment]
I'm closing this issue from lack of information.
