### ISSUE TITLE
Section 5.3: Order of fields in gdt struct should be switched

### ISSUE THREAD

**Issue by aritra0227** [OrdoFlammae/littleosbook-src#15]
According to the oswiki link: https://wiki.osdev.org/GDT, the size takes up the lower 16 bits.
Hence the gdt struct definition on _section 5.3_ should be the following instead:

```
struct gdt
{
    unsigned short size;
    unsigned int start_address;
} __attribute__((packed));
```

**Comment by OrdoFlammae** [comment]
Fixed in commit b6f9a9659654a9b29b6637c8cb140a836ab29d3f.
