### ISSUE TITLE
Bochs problem

### ISSUE THREAD

**Issue by zuolizhu** [OrdoFlammae/littleosbook-src#3]
Hi OrdoFlammae,
Thank you for keeping updating this littleosbook!

I run into the problem with Bochs, where I asked in [the original repo].(https://github.com/littleosbook/littleosbook/issues/94)

Is this the problem of the system? Should I use Ubuntu 11.04 instead of 16.04? 

Thank you!

**Comment by OrdoFlammae** [comment]
Not sure if it is **the** problem, but other people have had an issue with the line
```
section .text:
```
which should not have a colon after it,
```
section .text
```
Also, you should be fine using 16.04, since I ran the code in the book on Ubuntu 17.10.

**Comment by zuolizhu** [comment]
Removing the colon does not solve this problem. I will try it latter on other machine. Thank you so much OrdoFlammae!

**Comment by OrdoFlammae** [comment]
I'm going to go ahead and close this issue since it appears not to be causing the author any problems.
