### ISSUE TITLE
Pandoc Update

### ISSUE THREAD

**Issue by OrdoFlammae** [OrdoFlammae/littleosbook-src#5]
Pandoc has updated since I last worked on this, and, as a result, the make commands don't work anymore (missing arguments, removed arguments, etc.).

**Comment by umanovskis** [comment]
I know pandoc2 is stricter, but are there major issues? For me, just removing the `-S` switch is enough to build with pandoc 2.3 and get a HTML file that looks reasonable at the first glance.

**Comment by OrdoFlammae** [comment]
Well, yes, but you actually have to replace the -S switch, there's a reason it's there. This isn't a major issue, just an issue to remind me to work on it.
